### ISSUE TITLE
h8mail error unknown char

### ISSUE THREAD

**Issue by ucrersn** [khast3x/h8mail#102]
https://khast3x.club/tags/h8mail/

 [0m
         [95m Version 2.5.4 - "ROCKSMASSON.4"  [0m
[01m[38;5;33m [0m
[01m[38;5;69m         ._____. ._____.     ;____________;[0m
[01m[38;5;69m         | ._. | | ._. |     ;   h8mail   ;[0m
[01m[38;5;105m        | !_| |_|_|_! |     ;------------;[0m
[01m[38;5;105m        !___| |_______!  Heartfelt Email OSINT[0m
[01m[38;5;141m        .___|_|_| |___.    Use responsibly[0m
[01m[38;5;141m        | ._____| |_. | ;____________________;[0m
[01m[38;5;177m        | !_! | | !_! | ; github.com/khast3x ;[0m
[01m[38;5;177m        !_____! !_____! ;--------------------;[0m
[01m[38;5;213m        [0m
[01m[32m[>] [0mh8mail is up to date
[01m[31m[!] [0mMissing Target or URL

**Comment by khast3x** [comment]
Not using issue template, closing
