### ISSUE TITLE
cannot seem to get h8mail to work with the config file.

### ISSUE THREAD

**Issue by jepunband** [khast3x/h8mail#103]
*Issues not respecting the issue template will be closed without being read, thank you.*

### Checkbox

- [* ] I have thoroughly checked the answer is not in the [wiki](https://github.com/khast3x/h8mail/wiki).

### Env

* h8mail version: 2.5.4
* Python version: Python 2.7.18rc1
* Operating System: Kali Linux

### Description

Describe what you were trying to get done.
h8mail is not using h8mail_config.ini , even if the option has been set. It is still using scylla as source.
### What I Did
1. h8mail -g (to generate h8mail_config.ini)
2. updated the .ini file. (uncommented leak-lookup_pub)
3. h8mail -t mailtest@mail.com -c h8mail_config.ini
```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```
h8mail -t mailtest@mail.com -c h8mail_config.ini

**Comment by khast3x** [comment]
Hello,

Please retry using python 3.

Cheers
