### ISSUE TITLE
Searching for a specific email address through text files returns results with additional prefixes

### ISSUE THREAD

**Issue by shabbadont** [khast3x/h8mail#104]
Searching for test@test.com through text files, will return results for any email address with *test@test.com, as if there's an implied wildcard. I am not using the --loose nor am I using -q.

h8mail -t test@test.com -lb ./textfile.txt --sk

test@test.com search returns

123test@test.com
testtest@test.com
abctest@test.com

Is there a way to prevent this and just get results for test@test.com? It adds a lot additional of time to searches. Thank you.

*Issues not respecting the issue template will be closed without being read, thank you.*

### Checkbox

- [x] I have thoroughly checked the answer is not in the [wiki](https://github.com/khast3x/h8mail/wiki).

### Env

* h8mail version:
Latest
* Python version:
3
* Operating System:
Mac Catalina 

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
h8mail -t test@test.com -lb ./textfile.txt --sk
```

**Comment by khast3x** [comment]
Hello,
h8mail performs inclusive search, so you might indeed have this problem. h8mail does not support strict searching locally but I can maybe add it later.

Cheers!
