### ISSUE TITLE
no module named ui

### ISSUE THREAD

**Issue by chuckdu21** [khast3x/h8mail#11]
hi,
i installed h8mail with pip3 (because pip didnt work) and when i launch the program it says:

Traceback (most recent call last):
  File "h8mail.py", line 4, in <module>
    import ui
ImportError: No module named ui

**Comment by khast3x** [comment]
Hello,

`ui` is installed using pip3. If python cannot find `ui`, it's either because something went wrong at install, or that python cannot find it's location in your environment.

Please check: https://github.com/khast3x/h8mail#python-version-and-older-kali-systems

**Comment by coombed** [comment]
Hey all, just to add to the resolution on the "UI" issue...

To fix, I installed pip3 (sudo apt install python3-pip) and then re-ran the "pip3 install -r requirements.txt" command from within the h8mail folder.

To launch h8mail.py, you then type "python3 ./h8mail.py".

HTH!

**Comment by brunomarzz** [comment]
still not
