### ISSUE TITLE
Could not contact scylla.sh for test@gmail.com
500
<Response [500]>

### ISSUE THREAD

**Issue by YourS3npai** [khast3x/h8mail#111]
![Screenshot_20210109-003027_Termux.jpg](https://user-images.githubusercontent.com/68145560/104066112-e41d9e00-5211-11eb-9f8f-6577aeee82b8.jpg)
Can you help me please?

**Comment by khast3x** [comment]
Hello,

The source of the issue has been identified and should be fixed soon. I'll keep this updated.  


Cheers

**Comment by hyp3ri0n-ng** [comment]
@khast3x and I are fixing. Just did and should be good to go again!

**Comment by khast3x** [comment]
Can confirm, thanks @hyp3ri0n-ng !
Closing
