### ISSUE TITLE
scylla.so error

### ISSUE THREAD

**Issue by jepunband** [khast3x/h8mail#121]
*Issues not respecting the issue template will be closed without being read, thank you.*

### Checkbox

- [*] I have thoroughly checked the answer is not in the [wiki](https://github.com/khast3x/h8mail/wiki).

### Env

* h8mail version: 2.5.5
* Python version: Python 3.9.2
* Operating System: Kali

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

h8mail -t mail@email.com
```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.

[!] scylla.so error: mail@email.com
Expecting value: line 2 column 1 (char 1)
```

**Comment by khast3x** [comment]
Hello,

Scylla is currently offline while they are upgrading their back-end. If you go to scylla.so, you can read the following message from them:

```
We are very happy to announce that in our effort to continue providing free access to the world's largest breach dataset, we have made a number of changes. We are bringing on more resources, including developers, architects, and all that good stuff. It will take a few months to make some immediate improvements, but after that Scylla will be back online with all of it's 1.2+ Trillion glorious records.
```
