### ISSUE TITLE
Scylla.so

### ISSUE THREAD

**Issue by ksisomphone1** [khast3x/h8mail#122]
*Issues not respecting the issue template will be closed without being read, thank you.*

### Checkbox

- [x] I have thoroughly checked the answer is not in the [wiki](https://github.com/khast3x/h8mail/wiki).

### Env

* h8mail version: 2.5.5 - "ROCKMASSON.5"
* Python version: 3.9.2
* Operating System: Kali 2021.1

### Description

I was using h8mail to find password breaches on myself and I've read that scylla.so was down for sometime. During the run of my code, I used the command h8mail -t "my@email.com" -c h8mail_config.ini, this generated 18 breaches but scylla.so couldn't output the passwords for the breaches.

### What I Did

```
The Command I used was h8mail -t "my@email.com" -c h8mail_config.ini. 
In the 5th line, scylla.so is shown to be up and running, Ex.) **[>] scylla.so is up**
Then at the bottom of the code before being shown the output of the number of breaches found with my email, I'm greeted with the line; **[ ! ] syclla.so error: my@email.com. Expecting value: line 2 column 1 (char 1)**
I've updated and upgrade all my files and even did a git clone into the repository and did the setup.py and requirements.txt
I couldn't find any information relating to my issue and decided to reach out to you about it if you might have an idea on how I could fix this. I also tried explaining this as best as I could because screens
```

**Comment by wackybastard** [comment]
now service named scylla is down, for more information [check it](https://scylla.so/)
