### ISSUE TITLE
The page you're looking for could not be found (404)

### ISSUE THREAD

**Issue by xescar** [khast3x/h8mail#145]
*Issues not respecting the issue template will be closed without being read, thank you.*

### Checkbox

- [x] I have thoroughly checked the answer is not in the [wiki](https://github.com/khast3x/h8mail/wiki).

### Env

* h8mail version: Version 2.5.6 - "ROCKSMASSON.6"
* Python version: (python --version and python3 --version) Python 3.9.7 and (python2 --version) Python 2.7.18
* Operating System: Linux Mint 5.4.0-121

### Description

I have installed h8mail and checked a test email

Output says there was an error :
[!] scylla.so error: email@test.com
Expecting value: line 2 column 1 (char 1)

### What I Did

pip3 install h8mail

h8mail -t email@test.com

[>] h8mail is up to date
[~] Removing duplicates
[>] Targets:
[>] email@test.com
[>] scylla.so is up
[~] Target factory started for email@test.com
[~] [email@test.com]>[hunter.io public]
[>] Found 0 related emails for email@test.com using hunter.io (public)
[~] [email@test.com]>[scylla.so]
[!] scylla.so error: email@test.com
Expecting value: line 2 column 1 (char 1)

h8mail --debug -t test@test.email.com

[>] h8mail is up to date
[~] Removing duplicates
[>] Targets:
[>] test@test.email.com
[>] scylla.so is up
[~] Target factory started for test@test.email.com
 DEBUG: Created target object for test@test.email.com 
[~] [test@test.email.com]>[hunter.io public]

[@] DEBUG: Sent the following---------------------
{'User-Agent': 'h8mail-v.2.5.6-OSINT-and-Education-Tool (PythonVersion=3.9.7; Platform=Linux)'}
https://api.hunter.io/v2/email-count?domain=test.email.com GET None None

[@] DEBUG: Received the following---------------------

[@] https://api.hunter.io/v2/email-count?domain=test.email.com

[@] DEBUG: RESPONSE HEADER---------------------
Date: Thu, 30 Jun 2022 17:57:51 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
x-content-type-options: nosniff
x-download-options: noopen
x-permitted-cross-domain-policies: none
referrer-policy: strict-origin-when-cross-origin
permissions-policy: interest-cohort=()
access-control-allow-origin: *
access-control-allow-methods: GET, POST, PUT, DELETE, OPTIONS
access-control-allow-headers: Email-Hunter-Origin
Cache-Control: public, max-age=432000
etag: W/"3254b8b2a7dff999ed346cfba3d2586d"
x-request-id: d353b7c7-79ac-4e06-9283-07e44c714a4f
x-runtime: 0.026822
via: 1.1 google
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
CF-Cache-Status: HIT
Age: 128
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Server: cloudflare
CF-RAY: 7238c9670e15867a-MAD
Content-Encoding: br

[@] DEBUG: RESPONSE BODY---------------------
b'{\n  "data": {\n    "total": 1,\n    "personal_emails": 0,\n    "generic_emails": 1,\n    "department": {\n      "executive": 0,\n      "it": 0,\n      "finance": 0,\n      "management": 0,\n      "sales": 0,\n      "legal": 0,\n      "support": 0,\n      "hr": 0,\n      "marketing": 0,\n      "communication": 0\n    },\n    "seniority": {\n      "junior": 0,\n      "senior": 0,\n      "executive": 0\n    }\n  },\n  "meta": {\n    "params": {\n      "domain": "test.email.com",\n      "company": null,\n      "type": null\n    }\n  }\n}'
[>] Found 1 related emails for test@test.email.com using hunter.io (public)
[~] [test@test.email.com]>[scylla.so]

[@] DEBUG: Sent the following---------------------
{'User-Agent': 'h8mail-v.2.5.6-OSINT-and-Education-Tool (PythonVersion=3.9.7; Platform=Linux)', 'Accept': 'application/json'}
https://scylla.so/search?q=email:%20%22test@test.email.com%22 GET None None

[@] DEBUG: Received the following---------------------

[@] https://scylla.so/search?q=email:%20%22test@test.email.com%22

[@] DEBUG: RESPONSE HEADER---------------------
Content-Type: text/html; charset=utf-8
Permissions-Policy: interest-cohort=()
Vary: Origin
X-Content-Type-Options: nosniff
Date: Thu, 30 Jun 2022 17:57:52 GMT
Transfer-Encoding: chunked

[@] DEBUG: RESPONSE BODY---------------------
b'\n<!DOCTYPE html>\n<html>\n<head>\n  <meta content="width=device-width, initial-scale=1, maximum-scale=1" name="viewport">\n  <title>The page you\'re looking for could not be found (404)</title>\n  <style>\n    body {\n      color: #666;\n      text-align: center;\n      font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;\n      margin: auto;\n      font-size: 14px;\n    }\n\n    h1 {\n      font-size: 56px;\n      line-height: 100px;\n      font-weight: 400;\n      color: #456;\n    }\n\n    h2 {\n      font-size: 24px;\n      color: #666;\n      line-height: 1.5em;\n    }\n\n    h3 {\n      color: #456;\n      font-size: 20px;\n      font-weight: 400;\n      line-height: 28px;\n    }\n\n    hr {\n      max-width: 800px;\n      margin: 18px auto;\n      border: 0;\n      border-top: 1px solid #EEE;\n      border-bottom: 1px solid white;\n    }\n\n    img {\n      max-width: 40vw;\n      display: block;\n      margin: 40px auto;\n    }\n\n    a {\n      line-height: 100px;\n      font-weight: 400;\n      color: #4A8BEE;\n      font-size: 18px;\n      text-decoration: none;\n    }\n\n    .container {\n      margin: auto 20px;\n    }\n\n    .go-back {\n      display: none;\n    }\n\n  </style>\n</head>\n\n<body>\n  <img src="data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjEwIiBoZWlnaHQ9IjIxMCIgdmlld0JveD0iMCAwIDIxMCAyMTAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CiAgPHBhdGggZD0iTTEwNS4wNjE0IDIwMy42NTVsMzguNjQtMTE4LjkyMWgtNzcuMjhsMzguNjQgMTE4LjkyMXoiIGZpbGw9IiNlMjQzMjkiLz4KICA8cGF0aCBkPSJNMTA1LjA2MTQgMjAzLjY1NDhsLTM4LjY0LTExOC45MjFoLTU0LjE1M2w5Mi43OTMgMTE4LjkyMXoiIGZpbGw9IiNmYzZkMjYiLz4KICA8cGF0aCBkPSJNMTIuMjY4NSA4NC43MzQxbC0xMS43NDIgMzYuMTM5Yy0xLjA3MSAzLjI5Ni4xMDIgNi45MDcgMi45MDYgOC45NDRsMTAxLjYyOSA3My44MzgtOTIuNzkzLTExOC45MjF6IiBmaWxsPSIjZmNhMzI2Ii8+CiAgPHBhdGggZD0iTTEyLjI2ODUgODQuNzM0Mmg1NC4xNTNsLTIzLjI3My03MS42MjVjLTEuMTk3LTMuNjg2LTYuNDExLTMuNjg1LTcuNjA4IDBsLTIzLjI3MiA3MS42MjV6IiBmaWxsPSIjZTI0MzI5Ii8+CiAgPHBhdGggZD0iTTEwNS4wNjE0IDIwMy42NTQ4bDM4LjY0LTExOC45MjFoNTQuMTUzbC05Mi43OTMgMTE4LjkyMXoiIGZpbGw9IiNmYzZkMjYiLz4KICA8cGF0aCBkPSJNMTk3Ljg1NDQgODQuNzM0MWwxMS43NDIgMzYuMTM5YzEuMDcxIDMuMjk2LS4xMDIgNi45MDctMi45MDYgOC45NDRsLTEwMS42MjkgNzMuODM4IDkyLjc5My0xMTguOTIxeiIgZmlsbD0iI2ZjYTMyNiIvPgogIDxwYXRoIGQ9Ik0xOTcuODU0NCA4NC43MzQyaC01NC4xNTNsMjMuMjczLTcxLjYyNWMxLjE5Ny0zLjY4NiA2LjQxMS0zLjY4NSA3LjYwOCAwbDIzLjI3MiA3MS42MjV6IiBmaWxsPSIjZTI0MzI5Ii8+Cjwvc3ZnPgo="\n       alt="GitLab Logo" />\n  <h1>\n    404\n  </h1>\n  <div class="container">\n    <h3>The page you\'re looking for could not be found.</h3>\n    <hr />\n    <p>The resource that you are attempting to access does not exist or you don\'t have the necessary permissions to view it.</p>\n     <p>Make sure the address is correct and that the page hasn\'t moved.</p>\n     <p>Please contact your GitLab administrator if you think this is a mistake.</p>\n    <a href="javascript:history.back()" class="js-go-back go-back">Go back</a>\n  </div>\n  <script>\n    (function () {\n      var goBack = document.querySelector(\'.js-go-back\');\n\n      if (history.length > 1) {\n        goBack.style.display = \'inline\';\n      }\n    })();\n  </script>\n</body>\n</html>\n\n'
[!] scylla.so error: test@test.email.com
Expecting value: line 2 column 1 (char 1)

**Comment by khast3x** [comment]
Hello, as showed in the README's table of working services, scylla is currently unavailable. You can use alternative APIs as documented. Cheers
