### ISSUE TITLE
Facing some troubles against the local test 

### ISSUE THREAD

**Issue by SoftAddict** [khast3x/h8mail#15]
Great effort and work on the tool wish you all the best !  @khast3x 
As the title claims, 
I've been testing around with the normal lookup It's working great, however without showing passwords for obvious reasons, just breaches sources.  I couldn't get the services with api to work because they charge money for their API's as i noticed.
So, I downloaded the breachcompilation to actually go ahead and test it, I got the txt sorted and went ahead to test. I got these errors:
Warning: Breach compilation [Errno 2] No such file or directory: '/root/h8mail/BreachCompilation/query.sh': '/root/h8mail/BreachCompilation/query.sh'

Seems like the query.sh is missing so i got a query from here:  https://gist.github.com/nlitsme/6f138e72b328c28520d64d7e03f2d5f9

Later on, after several testings I ran this command as explained:
python h8mail.py -t targets.txt -bc ../Downloads/BreachCompilation/ --local
I got false breached signals with no passwords shown.

I know im missing something, will be glad if someone is able to point it out! 

Cheers

**Comment by khast3x** [comment]
Hello,

Did you download the 44GiB Torrent locally? The torrent as its the actual DB h8mail will search with the -bc option. The torrent also includes the aforementioned query.sh associated

**Comment by SoftAddict** [comment]
Hey, 

Thanks for replying !
I downloaded it from this link in the usage section of the tool,                         https://ghostbin.com/paste/2cbdn, I'm not sure if that's the correct one!

All i can see is a breachcompilation.7z, I uncompressed it, sorted it with these commands :

LC_ALL=C sort --parallel=8 -u breachcompilation.txt -o breachcompilation.sorted.txt
sed -i -e's/^\s*//' breachcompilation.sorted.txt

for some reason, the file has only a txt file, the rest of the files aren't available!
So, I guess this is where the issue presist from.

**Comment by SoftAddict** [comment]
> Hello,
> 
> Did you download the 44GiB Torrent locally? That's the "Breach Compilation", and is mandatory for the option.
> 
> The torrent is the actual DB h8mail will search with the `-bc` option.
> 
> The torrent also includes the aforementioned `query.sh` associated.
> 
> Best

Hey, 

Thanks for replying !
I downloaded it from this link in the usage section of the tool,                         https://ghostbin.com/paste/2cbdn, I'm not sure if that's the correct one!

All i can see is a breachcompilation.7z, I uncompressed it, sorted it with these commands :

LC_ALL=C sort --parallel=8 -u breachcompilation.txt -o breachcompilation.sorted.txt
sed -i -e's/^\s*//' breachcompilation.sorted.txt

for some reason, the file has only a txt file, the rest of the files aren't available!
So, I guess this is where the issue presist from.

**Comment by dkramer47** [comment]
I'm not exactly sure why, but I think it's probably because your breach compilation file is setup differently than what it expects.

Try using the same magnet link that I did to redownload it, I won't give it here, but just search "breach compilation download" on Google. I got mine off of raidforums.

Also, my usage of it is:
python3 h8mail.py -t youremail@domain.com -bc ./BreachCompilation -v -l

**Comment by SoftAddict** [comment]
> I'm not exactly sure why, but I think it's probably because your breach compilation file is setup differently than what it expects.
> 
> Try using the same magnet link that I did to redownload it, I won't give it here, but just search "breach compilation download" on Google. I got mine off of raidforums.
> 
> Also, my usage of it is:
> python3 h8mail.py -t [youremail@domain.com](mailto:youremail@domain.com) -bc ./BreachCompilation -v -l

Okay I'll check it out, and retry. 
Did you use these commands to sort it out or transform it to small parts because it's 44 gb i think
LC_ALL=C sort --parallel=8 -u breachcompilation.txt -o breachcompilation.sorted.txt
sed -i -e's/^\s*//' breachcompilation.sorted.txt

Or there is no need to do that?
Also how are you running your system is it virtual or dual because im using it on Vmware

Thanks!

**Comment by dkramer47** [comment]
For me it came pre-sorted, so all I had to do was run the command. I'm just running it a bootable usb, I find that I like being able to take it with me and plug it into any machine I might want to!

**Comment by SoftAddict** [comment]
> For me it came pre-sorted, so all I had to do was run the command. I'm just running it a bootable usb, I find that I like being able to take it with me and plug it into any machine I might want to!

Yeah I normally use bootables usb's, they're much reliable.
Anyhow i got it to work thanks for the replies!
it seems like the email i was trying to target is only breached with either a hash or salt included not as plain text whereas other targets proves that the method works fine!

Thanks!

**Comment by RomanNepal** [comment]
why am i getting -lb/--local-breach: at least one argument expected error? Help me I am really stuck
