### ISSUE TITLE
Warning: Breach compilation [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by jujdicek** [khast3x/h8mail#17]
hi guys so when i run the command _python h8mail.py -t (email@adress.com) -bc ../Downloads/BreachCompilation/ --local_ i get an error saying _Warning: Breach compilation [WinError 2] The system cannot find the file specified_
the breach compilation file is located in Downloads on my C: drive, i tried everything. any ideas how to solve this?

**Comment by khast3x** [comment]
You have to specify the path to the BC with the `-bc` option
