### ISSUE TITLE
'ui' has no attribute 'setup'

### ISSUE THREAD

**Issue by ANK1036Official** [khast3x/h8mail#18]
The script runs fine, up until I actually ask it to search the emails. Which it gives this error:

`Traceback (most recent call last):
  File "h8mail.py", line 228, in <module>
    ui.setup(verbose=args.verbosity)  # Show debug messages if -v True
AttributeError: module 'ui' has no attribute 'setup'
`

Quick note as well, not the same issue as the "No module named ui" incidents with issue 11.

**Comment by pretech86** [comment]
the same issue with me also how can i solve this

**Comment by khast3x** [comment]
Hey there please try the v2 branch, let me know if that helps. Cheers

**Comment by pretech86** [comment]
Sorry for that , what you mean by v2 branch

**Comment by khast3x** [comment]
Run `git checkout v2` inside the h8mail directory to do so.
