### ISSUE TITLE
Error: Request could not be made

### ISSUE THREAD

**Issue by TomasPhilippart** [khast3x/h8mail#20]
Hello, I am getting an error when running `python3 h8mail.py -t test@mail.com`. 

`Error: Request could not be made for test@mail.com HTTPSConnectionPool(host='haveibeenpwned.com', port=443): Max retries exceeded with url: /api/v2/breachedaccount/test@mail.com?truncateResponse=true (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f80a83d7780>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Traceback (most recent call last):
  File "h8mail.py", line 230, in <module>
    main(args)
  File "h8mail.py", line 200, in main
    breached_targets = target_factory(targets, api_keys)
  File "h8mail.py", line 146, in target_factory
    current_target.get_hibp()
  File "/root/h8mail/classes.py", line 75, in get_hibp
    response = self.make_request(url)
  File "/root/h8mail/classes.py", line 48, in make_request
    if response.status_code == 429:
UnboundLocalError: local variable 'response' referenced before assignment
`

![image](https://user-images.githubusercontent.com/10818830/54158884-7d779f80-4443-11e9-82e9-7e2a39de6d77.png)

**Comment by khast3x** [comment]
Hello,

Please check out the `v2` branch, as I did some major refactors including better headers, ideally not getting blocked by Cloudflare. Cheers
