### ISSUE TITLE
ui error 

### ISSUE THREAD

**Issue by pretech86** [khast3x/h8mail#21]
thanks for the tool but i have this error 

Traceback (most recent call last):
  File "h8mail.py", line 228, in <module>
    ui.setup(verbose=args.verbosity)  # Show debug messages if -v True
AttributeError: module 'ui' has no attribute 'setup'

**Comment by thewhiteh4t** [comment]
steps to reproduce : 
`pip3 install -r requirements.txt`
`python3 h8mail.py -t test@gmail.com`

**Comment by khast3x** [comment]
Hello,

Could you try the `v2` branch? Version is still in development but issue should be fixed

Run `git checkout v2` inside the h8mail directory to do so.

Cheers

**Comment by thewhiteh4t** [comment]
v2 is working properly!
