### ISSUE TITLE
Question - Weleakinfo hash/wild search 

### ISSUE THREAD

**Issue by unl1k3ly** [khast3x/h8mail#28]
Hi mate, awesome project! Thank you so much for coming up with this.

Wondering if you will be willing to accept anything else rather than an e-mail as target. From time to time, we search for hash, domain, name, company name etc...

Would you be looking into it ?

Cheers

**Comment by khast3x** [comment]
Hey there,  
Thanks for checking h8mail out!  
Yes it's on my roadmap. Don't expect it too soon though, I'm closing my h8mail sprint with this release.  
We'll see what the next sprint cycle brings!

Cheers

**Comment by khast3x** [comment]
Hey there,

These features are implemented in the upcoming 2.3 release. You can already pull the branch to try it out :)  
You'll want to look at the `-q` option.  

Cheers!
