### ISSUE TITLE
Future release features

### ISSUE THREAD

**Issue by khast3x** [khast3x/h8mail#29]
Ideas for future release:

* Check larger types of inputs with API services
  * username
  * hash
  * wildcard

* Check if running latest version of h8mail
  * perform/suggest update if not

* HTML report

**Comment by SolorzanoJose** [comment]
Now that collection 2 through 5 are public on some sites, do you plan on adding them?

**Comment by khast3x** [comment]
@SolorzanoJose If you've got them in `.gz` or `.txt` h8mail can already search through them with `-gz` or `-lb` respectively

**Comment by khast3x** [comment]
These features are implemented in the upcoming 2.3 release. You can already pull the branch to try it out
