### ISSUE TITLE
[WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by jujdicek** [khast3x/h8mail#32]
* h8mail version: 2.2
* Python version: Python 3.7.1
* Operating System: Windows 10

Whenever I execute the following command I get a WinError 193

_h8mail.exe -t email@email.com -bc D:\BC\BreachCompilation_

[>] Targets:
email@email.com
[~] Removing duplicates
[~] Target factory started for email@email.com
[!] Could not contact HIBP for email@email.com
403
[>] Found 0 related emails for email@email.com using Hunter.IO
[>] Found additional data with emailrep.io
[~] Looking up email@email.com in BreachCompilation
[!] Breach compilation
[WinError 193] %1 is not a valid Win32 application

**Comment by khast3x** [comment]
Hello,

The `-bc` is only supported on unix systems, as it uses a bash script provided with the BreachCompilation torrent.  
You can still use `-lb` (generic text search) with it, but it will be slower.
You can read about using it in the [dedicated section of the release write-up](https://khast3x.club/h8mail/2019/05/26/h8mail-release/?ref=readmebutton#breach-compilation)

Cheers
