### ISSUE TITLE
Can't open h8mail.py and HIBP not working for me

### ISSUE THREAD

**Issue by randysix** [khast3x/h8mail#33]
Hello,
I'm having two issues..

The first one is regarding h8mail.py
Whenever I run the commands:

apt-get install nodejs
git clone https://github.com/khast3x/h8mail.git
cd h8mail
pip3 install -r requirements.txt
python3 h8mail.py -h

It says the following:

python3: can't open file 'h8mail.py': [Errno 2] No such file or directory

The second one: regarding HIBP
Whenever I run the command:

h8mail -t [target@example.com]

It says the following in one of the lines:

[!] Could not contact HIBP for [target@example.com]
403

Any advice as to how to solve these two issues would be much appreciated.

**Comment by khast3x** [comment]
Hey there,  
Thank you for checking out h8mail.  
These instructions were to install and use h8mail v1.  
Now, h8mail uses `pip`, and installs itself when running `pip3 install h8mail` or running . It seems you still managed to get it working as per your second problem, so I'm guessing you did that too?  

As for your second problem, could you confirm which version of h8mail you are using? It should be in the banner when running it.

Cheers

**Comment by randysix** [comment]
Hello, thanks for the quick reply
Yes, about the README.. I did check it out, followed the instructions, but then got this HIBP error.. My h8mail version is 2.21.0.

Another thing that I noticed when reading through the write-up is that I can still read h8mail.py under the line "Version 2.0  -  'Birthday Update" in the GIFs of the 'Local Searching' section.. This got me quite confused, because when I run it myself it says 'h8mail', instead of 'h8mail.py'.. So maybe h8mail.py is a must?? Please let me know.

**Comment by khast3x** [comment]
Hello,   
That one is on me, the example GIFs require updating. Thank you for bringing it up. To be explicit, there is no `h8mail.py` anymore.  

As for the 403, maybe your IP is flagged? The next update will also have a `--debug` option so you'll be able to get more information. You can already try it using the 2.3 git branch, or wait a few days for the release. Let me know how things go. 

Cheers!

**Comment by randysix** [comment]
Hello.
Thanks for letting me know that h8mail.py no longer exists. Nice to hear about the incoming update too.

Now, about the 403 issue.. I really can't tell for sure wether my IP is flagged or not in HIBP since this has never happened to me before. I suspect it is indeed flagged (based on what I've been reading this is often the case..). If you know the solution to this problem I'd very much appreciate your help.

**Comment by owentl** [comment]
I too am getting the 403 error from HIBP.  I tried this on 2 different machines with same result after installing with pip.

Is this due to HIBP changing to v3 of their API and now requiring a key (which is paid from what I understand)?

**Comment by khast3x** [comment]
Hello @randysix and @owentl,

h8mail's new version has been released. Could you retry using the `--debug` option? This will dump the requests you are sending and receiving, and hopefully give us more clues for the 403.  

The HIBP API finishes tomorrow IIRC

**Comment by randysix** [comment]
Hello, 
It turns out I'm not geting the 403 anymore, but the 401 instead. From what I have read it might be because I haven't purchased the _HIBP_ key, thus I'm unauthorized.. So I'd say this isn't an issue anymore.

But now I have another doubt. 
I'm confused over the _configuration files_ topic. I have some keys apart from the default one that I've typed down and uncommented in the _config.ini_ text file. Then generated the _h8mail_config.ini_ text file and did exactly the same thing than before. 

After that, I ran the command:

**h8mail -t [example] -q [query] -c h8mail_config.ini**

But I'm only getting the results from the default _leak lookup pub_, and not from the other keys. 
By the way, I don't own any of the private keys, just the public ones.. Could this fact be causing this?  Or did I just do something wrong in the process? Please let me know, I'd appreciate your help.

(Btw, sorry if this doubt is misleading to the title of the issue)

**Comment by N1k0la1** [comment]
Same here. Getting the 401 error with a valid API Key. Running H8mail v2.3

**Comment by khast3x** [comment]
Hello,

In the [documentation](https://github.com/khast3x/h8mail#apis), the APIs with the key (:key:) symbol are APIs keys you need to purchase.  
You can find links in the [configuration file section](https://github.com/khast3x/h8mail#tangerine-configuration-file--keys) of the documentation.  
If you purchased an API key for haveibeenpwned, please keep in mind that they expire after 1 month.  


Cheers

**Comment by iXanderM** [comment]
Im changing specific parts that will reveal sensitive information into ``beep``
So I did ```$ winpty python.exe h8mail -t beep@beep.com```
and it said ``Traceback (most recent call last):
  File "C:\Users\beep\AppData\Local\Programs\Python\Python38\lib\runpy.py", l
ine 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\beep\AppData\Local\Programs\Python\Python38\lib\runpy.py", l
ine 87, in _run_code
    exec(code, run_globals)
  File "h8mail\__main__.py", line 2, in <module>
    from .utils.run import main
ImportError: attempted relative import with no known parent package```
help me out please thank you :)

**Comment by flyinggoatman** [comment]
Hey so I've installed the program with the readme on the github but the command h8mail but it says that is not a command.

here are all the commands I used 

https://pastebin.com/2yNRcds8
`       1@kali:~/Apps/h8mail$ pip3 install h8mail
Requirement already satisfied: h8mail in /home/fly/.local/lib/python3.8/site-packages (2.5.4)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from h8mail) (2.23.0)
1@kali:~/Apps/h8mail$ h8mail
bash: h8mail: command not found
1@kali:~/Apps/h8mail$ h8mail -h
bash: h8mail: command not found
1@kali:~/Apps/h8mail$ pip3 h8mail
ERROR: unknown command "h8mail"
1@kali:~/Apps/h8mail$ python3 h8mail
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "h8mail/__main__.py", line 2, in <module>
    from .utils.run import main
ImportError: attempted relative import with no known parent package
1@kali:~/Apps/h8mail$ `

**Comment by khast3x** [comment]
@flyinggoatman it seems your pip3 installation is not complete, so does not know where to look for h8mail.  
Please check the Troubleshooting section for OSX in the wiki for a workaround.

Cheers

**Comment by flyinggoatman** [comment]
Ty

**Comment by flyinggoatman** [comment]
> @flyinggoatman it seems your pip3 installation is not complete, so it does not know where to look for h8mail.
> Please check the Troubleshooting section for OSX in the wiki for a workaround.
> 
> Cheers

Is this what the installation process should look like 

`1@kali:~$ sudo apt-get --reinstall install python3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libcdio18 libcfitsio8 libilmbase24 libopenexr24 libpoppler82 linux-image-5.5.0-kali2-amd64 openjdk-8-jre
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 60 not upgraded.
Need to get 0 B/63.7 kB of archives.
After this operation, 0 B of additional disk space will be used.
(Reading database ... 388209 files and directories currently installed.)
Preparing to unpack .../python3_3.8.2-3_amd64.deb ...
running python pre-rtupdate hooks for python3.8...
Unpacking python3 (3.8.2-3) over (3.8.2-3) ...
Setting up python3 (3.8.2-3) ...
running python rtupdate hooks for python3.8...
/usr/share/legion/app/auxiliary.py:273: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if text is not '' and text is not ' ':
/usr/share/legion/app/auxiliary.py:273: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if text is not '' and text is not ' ':
/usr/share/legion/app/auxiliary.py:285: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if text is not '' and re.search("[^A-Za-z0-9_-]+", text) is None:
/usr/share/legion/app/auxiliary.py:291: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if text is not '' and re.search("[^A-Za-z0-9_() -]+", text) is None:
/usr/share/legion/app/cvemodels.py:55: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if not len(self.__cves) is 0:
/usr/share/legion/app/hostmodels.py:43: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if not len(self.__hosts) is 0:
/usr/share/legion/app/processmodels.py:43: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if not len(self.__processes) is 0:
/usr/share/legion/app/scriptmodels.py:44: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if not len(self.__scripts) is 0:
/usr/share/legion/app/servicemodels.py:40: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if not len(self.__services) is 0:
/usr/share/legion/app/servicemodels.py:184: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if not len(self.__serviceNames) is 0:
/usr/share/responder/settings.py:209: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if len(self.NumChal) is not 16 and not "random":
/usr/share/responder/tools/MultiRelay.py:418: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if data.find("NTLM") is not -1:
/usr/share/responder/tools/MultiRelay.py:423: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if data.find("NTLM") is not -1:
/usr/share/responder/tools/RunFingerPackets.py:14: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if PY2OR3 is "PY2":
running python post-rtupdate hooks for python3.8...
Processing triggers for kali-menu (2020.3.2) ...
Processing triggers for man-db (2.9.3-2) ...
`

**Comment by flyinggoatman** [comment]
Fixed i ran "sudo apt upgrade" and it seemed to patch the problem.

**Comment by ugur342** [comment]
> sudo apt upgrade

@flyinggoatman I tried that and so many files were downloading but then it ran into an error saying failed to fetch..... I also checked my storage and i had 300 mb left could it be because of that? if it is what do i do? I am a mac user running kali linux. SHould i get an external hard drive?
