### ISSUE TITLE
Error on local data

### ISSUE THREAD

**Issue by C4PT41ND34DP00L** [khast3x/h8mail#36]
* h8mail version: 2.2.1
* Python version: 3.6
* Operating System: Parrot OS

### Description
I installed with pip3

I am trying to run a batch of emails through the local data
h8mail -t '/home/username/Documents/Target.txt' -bc '/home/username/Documents/BreachCompilation' --local

h8mail: error: argument -lb/--local-breach: expected at least one argument

**Comment by C4PT41ND34DP00L** [comment]
I got it working with the -sk flag after doing sudo pip3 install h8mail

**Comment by khast3x** [comment]
Hello,  

Thank you for keeping the issue updated. By any chance, using the `.py` at the end is deprecated since version 2.0, maybe its also part of the issue. None the less glad you shared your fix.  
Cheers!
