### ISSUE TITLE
Could not contact HIBP

### ISSUE THREAD

**Issue by FlappyCheese** [khast3x/h8mail#40]
* h8mail version: 2.3
* Python version: Python 3.7.4
* Operating System: Kali Linux

### Description
I am running a single target against a user name, 

### What I Did
h8mail -t <email_address>
[>] Targets:
<email_address>
[~] Removing duplicates
[~] Target factory started for <email_address>
[~] HIBP free tier will stop working on the 2019/08/18
[~] You can already use a purchased API key using h8mail (config file)
[!] Could not contact HIBP for <email_address> 401

Unfortunately I do not know why there is a 401 error, it does tell me that there are breachs found (13 elements) but with no information, as see in your screen shots when you run the command. 

You advise for this n00b using your tool would be awesome.

**Comment by khast3x** [comment]
Hello,

Are you using a HIBP key? Or do you have a configuration file with a `hibp` key in it in the same folder?

Cheers

**Comment by FlappyCheese** [comment]
Hi khast3x,
I think that is my issue. I am not using a HIBP key.
Rookie mistake.
