### ISSUE TITLE
h8mail- "not compromised"- while searching on target

### ISSUE THREAD

**Issue by Forte577** [khast3x/h8mail#45]
* h8mail version:2.4.1
* Python version: both  2.7.17 and 3.7.4
* Operating System: Kali

### Description

I´m new at this, and aparrently h8mail is running well (not explicit errors during install nor execution) but i have some questions.

i did find 3 security breaches using haveibeenpwned on targets mail
but h8mail dont find anything, it says "not compromised"

i think im missing the whole point of this wonderful tool.

thank you, haunter

### What I Did

```
if i use another accounts that i find on internet in some h8mail tutorials and they did retrive results!!

```

**Comment by XiuYee** [comment]
Yup I've got the same issue

**Comment by khast3x** [comment]
Hello,

Few things. First, HIBP results vary from the web interface and the API (its mentioned it the HIBP documentation IIRC).  

Also, h8mail uses scylla.sh and emailrep.io to fetch breach results. h8mail indexes multiple data types as data breach counters, not just passwords.  
An example is found associated social presence from emailrep.io counts as a breach.  If using premium APIs this can include physical address etc.  

In some cases, h8mail has access to richer data than HIBP, incrementing the breach counter more. If that is not that case, you can use a HIBP API key with h8mail directly, the results will be included in the breach count.

Hope this helps, cheers! :wave:

**Comment by BraveWojtek** [comment]
Hi, I tried to use the tool, everything works fine (no errors), except there is no data even when I take a mail from one of text files of COMB database. I use PepperMint 10 64-bit, the newest versions of python and  h8mail. Any ideas?
