### ISSUE TITLE
Feature Request - Addition of Dehashed API

### ISSUE THREAD

**Issue by staxmood** [khast3x/h8mail#47]
* h8mail version:***
* Python version:***
* Operating System:***

### Description

Love using the program but would like the ability to run dehashed as another site to pull information from.

https://dehashed.com/docs

**Comment by khast3x** [comment]
Hello,

I have tried to contact their team to integrate but am currently waiting for a reply.  
Cheers!

**Comment by khast3x** [comment]
Will be included in next release, already available to test in the 2.5 branch. Cheers!

**Comment by staxmood** [comment]
Thanks much! Excited to test it out.
