### ISSUE TITLE
will it show the breached passwords?

### ISSUE THREAD

**Issue by jepunband** [khast3x/h8mail#48]
* h8mail version: 2.4.1
* Python version: python 2 & 3
* Operating System: Linux

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

python3 -m h8mail -t emailadd@hotmail.com -c config.ini

[>] Showing results for emailadd@hotmail.com
LEAKLOOKUP_PUB |emailadd@hotmail.com > myfitnesspal.com
LEAKLOOKUP_PUB |emailadd@hotmail.com > netlog.com
LEAKLOOKUP_PUB |emailadd@hotmail.com > jobstreet.com
__________________________________________________________________________________________
                                   Session Recap:  

                 Target                  |                   Status                  
__________________________________________________________________________________________

       emailadd@hotmail.com         |          Breach Found (3 elements)      

am i able to see the passwords for these breached sites?

**Comment by khast3x** [comment]
Hello,

You can view which data is returned by each provider [in the documentation here](https://github.com/khast3x/h8mail#APIs).  
You are using the Leak-lookup **public** key, which returns the number of hits in their DB only. If you wish to view the results, you need to purchase a full API key.  

Cheers!
