### ISSUE TITLE
Getting syntax error on newest version

### ISSUE THREAD

**Issue by duartemvix** [khast3x/h8mail#54]
* h8mail version: 2.5
* Python version: 3.5.2
* Operating System: Ubuntu 16.04

### Description

Trying to execute a command like, h8mail -h, did not work properly. I'm not sure if this error is really anything significant but I'm unfamiliar with Python so I decided to ask.

### What I Did

Created a virtual environment venv on user home folder using

`virtualenv -p /usr/bin/python3 venv`
then went in there doing
`cd venv`
`source bin/activate`
`pip3 install h8mail`
`h8mail -h`

This was the response

Traceback (most recent call last):
  File "/home/matt/venv/bin/h8mail", line 5, in <module>
    from h8mail.__main__ import main
  File "/home/matt/venv/lib/python3.5/site-packages/h8mail/__main__.py", line 2, in <module>
    from .utils.run import main
  File "/home/matt/venv/lib/python3.5/site-packages/h8mail/utils/run.py", line 10, in <module>
    from .breachcompilation import breachcomp_check
  File "/home/matt/venv/lib/python3.5/site-packages/h8mail/utils/breachcompilation.py", line 18
    c.info_news(f"Looking up {t.target} in BreachCompilation")
                                                            ^
SyntaxError: invalid syntax

**Comment by khast3x** [comment]
Hello,
You do not really need venvs as h8mail only uses the `requests` package.  
There is a wiki with a the detailed instructions.  
Please check the [Install instructions](https://github.com/khast3x/h8mail/wiki/Install) which should have all the steps you need. Check out [Troubleshooting](https://github.com/khast3x/h8mail/wiki/Troubleshooting) if needed.

Cheers

**Comment by duartemvix** [comment]
I just installed through pip3 but without venvs this time. I'm still
getting the same error.

But it doesn't appear to be anything serious rather than just a syntax
error.

Traceback still returns:

File
"/home/matt/.local/lib/python3.5/site-packages/h8mail/utils/breachcompilation.py",
line 18
    c.info_news(f"Looking up {t.target} in BreachCompilation")
                                                            ^
SyntaxError: invalid syntax

Em sex., 6 de mar. de 2020 às 09:17, ktx <notifications@github.com>
escreveu:

**Comment by khast3x** [comment]
If you type `pip3 show h8mail -v` you'll see that it requires either python 3.6 or 3.7.  
From your logs it seems you are running an older python version (3.5)

Cheers

**Comment by duartemvix** [comment]
Thanks, that was it. I managed to install it after getting python 3.7.

Have a great day.

Em sex., 6 de mar. de 2020 às 13:30, ktx <notifications@github.com>
escreveu:
