### ISSUE TITLE
issue with H8mail

### ISSUE THREAD

**Issue by dieao** [khast3x/h8mail#57]
* h8mail version:2.5
* Python version:3
* Operating System:Parrot

### Description

I followed the instructions to the T but it still isnt working? it says the following errors below.

```
user@parrot]─[~/h8mail]
└──╼ $pip install -r requirements.tx
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.tx'
┌─[✗]─[user@parrot]─[~/h8mail]
└──╼ $python h8mail.py -h
python: can't open file 'h8mail.py': [Errno 2] No such file or directory
┌─[✗]─[user@parrot]─[~/h8mail]
└──╼ $pip install -r requirements.txt
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
┌─[✗]─[user@parrot]─[~/h8mail]
└──╼ $python3 h8mail.py -h
python3: can't open file 'h8mail.py': [Errno 2] No such file or directory
┌─[✗]─[user@parrot]─[~/h8mail]
└──╼ $

 here.
```

**Comment by khast3x** [comment]
Hello,

You may be following deprecated instructions as there is no `h8mail.py` file since version 2.  
You can follow the up-to-date instructions from the [official wiki here](https://github.com/khast3x/h8mail/wiki/Install).

Cheers
