### ISSUE TITLE
DeHash API... Help please

### ISSUE THREAD

**Issue by mrmoofo123** [khast3x/h8mail#58]
* h8mail version: 2.5 "ROCKSROCKSMASSON"
* Python version: 3.7.7
* Operating System: Kali Linux 2020.1

### Description

How do i make get my dehash API to work? i have inserted my "dehash_key" in h8mail_config.ini. what do i insert in "dehash_email" ? and how do i run it with the API?

**Comment by khast3x** [comment]
Hello,

Please use the email associated with your Dehashed account.

Regards,
