### ISSUE TITLE
Cant get h8mail to show cleartext passwords

### ISSUE THREAD

**Issue by usermanbigman** [khast3x/h8mail#60]
* h8mail version: the latest
* Python version: 3
* Operating System: windows 10 / ubuntu Microsoft store variant

### Description

Trying to find my own accounts passwords and although breaches have been detected I cant actually see the clear text password to confirm that is not a false positive.

### What I Did

I ran python3 -m h8mail -t email@example.com -o Desktop

Program was like: found a breach. writing to CSV output. but no output or password was outputted? Please help.
```
```

**Comment by khast3x** [comment]
Fixed with this release.  
Check the wiki for [update instructions](https://github.com/khast3x/h8mail/wiki/Install#update).  
Cheers
