### ISSUE TITLE
Even after deleting the piece of code the same is executed

### ISSUE THREAD

**Issue by amartya89** [khast3x/h8mail#63]
Hi @khast3x 

Looking for your kind help. I am trying to modify the DEHASHED section in classes.py in my local copy. As i have stated in my previous issue #62 that requests.get is not returning anything in case of Dehash, hence i tried to check the same in another way. 

I have commented the make_request call from get_dehashed fucntion. But still o improvement. Then i have executed in debug and saw, the old method is getting called.

Am i missing anything? Is there anywhere else i need to change/ update anything to get my new chunk of code working?

Earnestly looking for your help at the earliest please.

Regards

**Comment by khast3x** [comment]
Hello,

Fixed with PR #97 .
Run pip3 install --upgrade h8mail to update h8mail to the latest version (2.5.4).

Cheers!
