### ISSUE TITLE
maintainer of scylla here with username/password for everyone

### ISSUE THREAD

**Issue by acaceres2176** [khast3x/h8mail#64]
### What I Did

I closed off scylla because stupid script kiddies were being stupid. Any user of h8mail is welcome to use this however, as I'm confident you're not stupid script kiddies :). The u/p you all may use:

sammy / BasicPassword!

Hope you all continue to enjoy scylla.sh. Reach me at acaceres@0-sec.net with any questions!

**Comment by Blakeboy02** [comment]
Thanks a lot!

**Comment by khast3x** [comment]
Hey @acaceres2176,  
Many thanks for sharing this! 🌱    
Would you rather I hardcode it in h8mail, or have it manually set by the user (config file)?  

Cheers!

**Comment by acaceres2176** [comment]
go ahead and hard-code it if you could. I'm getting flooded by users and h8mail is a pretty legit application with a good userbase!

**Comment by ZerberusSec** [comment]
Thats really great, thanks!

**Comment by khast3x** [comment]
Fixed with this release.  
Check the wiki for [update instructions](https://github.com/khast3x/h8mail/wiki/Install#update).  
Cheers
