### ISSUE TITLE
Doesn't work after update

### ISSUE THREAD

**Issue by elazzzzyy** [khast3x/h8mail#67]
* h8mail version: 2.5.1 ROCKSMASSON.1
* Python version: 3.6.9
* Operating System:ubuntu 16.04

### Description

after doing the --upgrade command my h8mail was up to date and I ran my email that I know is compromised and it said not compromised and that Scylla is down like it did in the previous version before the fix. I am not being rate limited either.

### What I Did

```
cd h8mail
h8mail -t mycompromisedemail@example.com -k "emailrep=mykey"

output : [>] h8mail is up to date
[~] Removing duplicates
[>] Targets:
[>] mycompromisedemail@example.com
[>] Found emailrep configuration key
[~] scylla.sh is down, skipping
[~] Target factory started for mycompromisedemail@example.com
[~] [mycompromisedemail@example.com]>[hunter.io public]
[>] Found 0 related emails for mycompromisedemail@example.com using hunter.io (public)

 __________________________________________________________________________________________

[>] Showing results for mycompromisedemail@example.com

[~] No results founds
```

**Comment by khast3x** [comment]
Looks ok, it was probably because of initial post-update load.

**Comment by elazzzzyy** [comment]
still isn't working, says my compromised email is not compromised and that Scylla is still down.

**Comment by perroviejo-bit** [comment]
i have the same issue, have you discovered how to fix it? @elazzzzyy

**Comment by elazzzzyy** [comment]
> 
> 
> i have the same issue, have you discovered how to fix it? @elazzzzyy

Yeah I bought a 3080 and a 5900x and idk but that fixed it but I just updated to 2.5.5 ROCKSMASSON.5 and it says scylla.so is down although it use to be scylla.sh idk why it changed and it also says my compromised email isn't so idk.

**Comment by perroviejo-bit** [comment]
so the issue might be related to our ISP, don't ypu think so?

**Comment by khast3x** [comment]
scylla.sh has move to scylla.so as [mentioned by the author](https://twitter.com/_hyp3ri0n/status/1352330378774781954?s=20). Unfortunately, it seems the service is currently offline on both domains. This should be fixed some time soon.  
In the meantime I suggest looking into [API Keys](https://github.com/khast3x/h8mail#APIs).

Cheers!

**Comment by elazzzzyy** [comment]
Ah right, I thought .sh and .so, the both of them were for seeing the password but other services were for detecting if they'd even been compromised.
