### ISSUE TITLE
emailrep does not activate

### ISSUE THREAD

**Issue by ZerberusSec** [khast3x/h8mail#68]
* h8mail version:
2.5.1
* Python version:
3.8.2
* Operating System:
Kali Linux

### Description

I started a search with a activated emailrep API key (through config) but h8mial doesnt check emailrep.io

### What I Did

h8mial -t maillist.txt -c h8mail_config.ini -o /output/out01.csv

**Comment by khast3x** [comment]
Hello,

Thank you for reporting the issue.  
Should be fixed with the 2.5.2 release [here](https://github.com/khast3x/h8mail/releases/tag/2.5.2).
