### ISSUE TITLE
hello 

### ISSUE THREAD

**Issue by arsenidzee** [khast3x/h8mail#72]
* h8mail version: last 10.05.2020
* Python version: 3
* Operating System: termux android

### Description

hello bro, im dont understand how add api key,how get it, sorry for my english, im bad speak!
can you say plz

**Comment by khast3x** [comment]
Hello,

At [the end of the README.md](https://github.com/khast3x/h8mail#tangerine-usage-examples) you will find multiple usage examples, including with API keys.

You can read more about using API keys in the dedicated [Wiki page](https://github.com/khast3x/h8mail/wiki/Using-APIs).  

Cheers
