### ISSUE TITLE
h8mail: error: argument -lb/--local-breach: expected at least one argument

### ISSUE THREAD

**Issue by dantenincevic** [khast3x/h8mail#73]
I'm running h8mail with docker on MacOS Catalina and I've downloaded a breach compilation folder. When I run:  

```docker run -ti kh4st3x00/h8mail -t john@gmail.com -bc '/Users/kristian/Desktop/BreachCompilation'  --local```

I get the following error:

```h8mail: error: argument -lb/--local-breach: expected at least one argument```

I have no idea why this is happening.

**Comment by khast3x** [comment]
Hello,

It seems you are not mounting the volume containing the breach compilation to the docker container running h8mail.  
This is typically done using `-v`.  
You can read more about using h8mail with Docker [in this blog post](https://khast3x.club/posts/2019-06-07-docker-h8mail/).

Cheers
