### ISSUE TITLE
Python 3.5 support

### ISSUE THREAD

**Issue by pielgrzym** [khast3x/h8mail#77]
* h8mail version:
* Python version:
* Operating System:
Debian

### Description

It's really laborous to get h8mail working on Debian systems just for some syntax sugar from python 3.6 and newer. Any commit I could refer to for easier backporting to python 3.5?

**Comment by khast3x** [comment]
Hello,

Not that I can think of. You can use docker if you really wish to keep working with older python versions locally. Or just rent a VPS.    
Reading your opinion it seems you are knowledgable in writing code. Feel free to fork the project and remove the syntax sugar yourself, everything's in the repo.

Cheers
