### ISSUE TITLE
Is this normal?

### ISSUE THREAD

**Issue by iXanderM** [khast3x/h8mail#83]
* h8mail version:latest version 4 days ago
* Python version:3.8
* Operating System:Win 10

### Description

Describe what you were trying to get done: Find the passwords

Paste the command(s) you ran and the output.``` ~winpty python.exe -m h8mail -t test@gmail.com
```
Is this normal? I dont see any passwords here, dont know what to do, sorry for the trouble but please help me out, thanks! https://imgur.com/tzaX795 < Vid of what screen looks like

**Comment by khast3x** [comment]
Hello,

From the video it seems h8mail found passwords. The default Windows terminal is known to have a hard time with ANSI colors. Please check the [Troubleshooting](https://github.com/khast3x/h8mail/wiki/Troubleshooting#windows) section as it is addressed with solution.  

Feel free to re-open ticket if problem persists.


Cheers
