### ISSUE TITLE
Hunter.io Private API Key Only Chasing/Finding 10 Emails

### ISSUE THREAD

**Issue by Hmonto** [khast3x/h8mail#84]
* h8mail version: 2.5.2
* Python version: 3.8.2
* Operating System: Kali Linux

### Description

I am trying to chase emails with hunter.io using the -ch command, but it only ever chases and adds a max of 10 related emails to the target list, always the same emails, even if around 200 related emails were found. I currently am using an API key connected to a paid account. I am just checking to make sure this is normal, or if something can be done to fix this.

### What I Did

```
h8mail -t 'location of target file' -c 'location of config file' -o 'output destination' -ch 2 (any more than 2 here and the program begins to endlessly loop)
```

**Comment by khast3x** [comment]
Hello,

hunter feeds emails sharing the same domain name as the target, if you have multiple targets of the same domain name, hunter should answer with the same results since the targets are part of the same domain.   
h8mail should skip duplicates though. Is this the case?  

The hunter chasing method was part of the first h8mail versions and might not have aged for the better. Furthermore, chasing is done recursively for performance, but can also be somewhat overwhelming if pushed above a certain amount of iterations. It should be used with one or just a few targets.

Cheers

**Comment by Hmonto** [comment]
So what will happen is I will do a search on hunter.io's website for a domain name and it will give me, say, 80 results. The hunter.io public search that h8mail does will show me this same number, 80. But when the hunter.io private search runs on h8mail, it will only return 10 of those 80 emails the public search found.

I actually think I know where this issue is stemming from, but I am not sure if it's currently possible to fix as h8mail is now. The issue I think is that, with hunter.io's private model, exporting 10 emails with the same domain is equivalent to one "request" in their request-based system. So when h8mail is using hunter.io's private API key, its only issuing one request, instead of (as per my sample situation above) 8 requests for all 80 emails. Is there something I am missing that could fix that in h8mail in its current form?

Thanks so much for your help @khast3x !

**Comment by khast3x** [comment]
Good job on the reverse engineering :smile:   
Yes that was the issue. All in all I remember implementing this and stopping at the "good enough" stage.  I don't think I'll be updating this as it could become annoying for hunter.  
Alternatively, you can use the `--power-chase` option when doing a general domain search, either with Scylla or [premium services that allow domain search](https://github.com/khast3x/h8mail/wiki/Using-APIs#api-providers---full-breach-data), like so:  
```bash
$ h8mail -t test.com -q domain --chase 2 --power-chase
```
Power-chase will chase any email returned from the query.  

Closing the issue, but feel free to re-open or comment if you have additional questions.  

Cheers!

**Comment by Hmonto** [comment]
Thank you for the feedback and advice! I can continue on manually, was just making sure there was not some glaringly obvious thing I wasn't seeing.
