### ISSUE TITLE
New intelX API

### ISSUE THREAD

**Issue by usermanbigman** [khast3x/h8mail#93]
### Checkbox

- [ Y ] I have thoroughly checked the answer is not in the [wiki](https://github.com/khast3x/h8mail/wiki).

### Env

* h8mail version: 2.5.3
* Python version: 3.8
* Operating System: ParrotOS

### Description

Added my 7 day free key of intelX too h8mail_config.ini,
Didn't work.

### What I Did

```
h8mail -t 123@gmail.com -c '/home/me/h8mail/h8mail_config.ini

After 240s (because scylla down) 
I got results back and in the sections where it tells you if it found anything related to target nothing popped up saying intelX, didn't return a false (not found anything) either.
```

**Comment by khast3x** [comment]
Hello,

Same as for issue #92, please use `--skip` while the default API is down.  

Cheers
