### ISSUE TITLE
Can you please add breachdirectory?

### ISSUE THREAD

**Issue by SU1C1D3** [khast3x/h8mail#96]
can you please add an api from https://breachdirectory.tk/? it is free and idk how to do it

**Comment by khast3x** [comment]
Hello,

Thanks for the heads-up, I'll check it out.

Cheers

**Comment by khast3x** [comment]
Hello,

After exchanging emails with the author, it seems the API is not yet functional.  
The author should notify me when it will be the case.

Cheers

**Comment by SU1C1D3** [comment]
Alright,thank you

**Comment by khast3x** [comment]
Hello,

The API will be integrated in the upcoming update.

Cheers
