### ISSUE TITLE
API keys

### ISSUE THREAD

**Issue by elazzzzyy** [khast3x/h8mail#98]
*Issues not respecting the issue template will be closed without being read, thank you.*

### Checkbox

- [Y] I have thoroughly checked the answer is not in the [wiki](https://github.com/khast3x/h8mail/wiki).

### Env

* h8mail version: 2.5.4
* Python version: 3.8
* Operating System: ubuntu WSL

### Description

Tried adding API keys, even on multiple other OS like parrot, kali.

### What I Did

```
h8mail -g 
added all of my API keys
ran a query h8mail -t example@example.com
and h8mail never ran the API keys, only the default public keys that come with h8mail.
```

**Comment by khast3x** [comment]
Hello,

As [shown in the wiki examples](https://github.com/khast3x/h8mail/wiki/Using-APIs#configuration-file--keys), you need to use `-c h8mail_config.ini`.  
The `-c` argument points to your configuration file, and tells h8mail to use the API keys.  

Furthermore, you can alternatively use `-k` and pass the keys directly from CLI.

You can find more usage examples at the bottom of the README homepage.  

Cheers
